### ISSUE TITLE
Issue on windows

### ISSUE THREAD

**Issue by charlotte-bone** [derhasi/composer-preserve-paths#1]
Hi, I'm trying to use with Windows, however I get a memory size exhausted error.  It looks as though it gets stuck in a constant loop because it doesn't ever reach the break condition.  If you replace the line below (line 234 of PathPreserver.php):

if ($folder === '.' || $folder === '/') {

with:

if ($folder === '.' || $folder === '/' || $folder === 'C:\\\') {

It solves the issue.

It'd be great if this could be updated!

Thanks,
Charlotte.

**Comment by derhasi** [comment]
Thanks for posting the issue. I'm currently not sure, how to deal with situations, where C:\\ is not the disc a windows user is working on. Would need to have closer look on that on a windows machine.

**Comment by graebermedien** [comment]
Alternative on Windows, check against

if ($folder === '.' || $folder === '/' || strpos($folder, ':\')) {


to ?
