### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by CindyConway** [derhasi/composer-preserve-paths#12]
When I install a Drupal modules I get:

Deprecation Notice: The callback derhasi\Composer\Plugin_composer_tmp1::prePackage declared at phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code accepts a Composer\Script\PackageEvent but pre-package-install events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:317

An example of command I am using to do the install: $composer require drupal/geofield:7.x

**Comment by impol** [comment]
+1

**Comment by impol** [comment]
Here is a PR #11

**Comment by davidsparks** [comment]
[This fork](https://github.com/drustack/composer-preserve-paths) also seems to address this issue.
