### ISSUE TITLE
Updating Drupal core causes duplicate sites dir

### ISSUE THREAD

**Issue by michaelfavia** [derhasi/composer-preserve-paths#4]
I've isolated it to a reproducible test case. If you toggle the required package drupal/drupal from 7.38 to 7.36 (or any other version) and composer update it places the sites folder from the drupal core download at the path: "ROOT/sites". In other words the directory that comes with drupal that is usually the ROOT/sites directory can now be found at "ROOT/sites/sites". I'm very happy to help or PR but I'm not yet sure how your plugin works. I assume it should merge (preferring preserved directories) or discard the directory? I'm available on IRC or hangouts at michaelfavia. Thanks for the useful plugin. Best, -mf

Relevant section of my composer.json:

```
  "extra": {
    "custom-installer": {
      "drupal-module": "docroot/sites/all/modules/contrib/{$name}/",
      "drupal-theme": "docroot/sites/all/themes/contrib/{$name}/",
      "drupal-library": "docroot/sites/all/libraries/{$name}/",
      "drupal-drush": "docroot/sites/all/drush/{$name}/",
      "drupal-profile": "docroot/profiles/{$name}/",
      "drupal-core": "docroot/"
    },
    "preserve-paths": [
      "docroot/sites/all/modules",
      "docroot/sites/all/modules",
      "docroot/sites/all/themes",
      "docroot/sites/all/libraries",
      "docroot/sites/all/drush",
      "docroot/sites/all/vendor",
      "docroot/sites/default/settings.php",
      "docroot/sites/default/files"
    ],
```

**Comment by derhasi** [comment]
@michaelfavia could you fix that issue?
