### ISSUE TITLE
Composer throws an exception when attempting to delete files instead of renaming the dir

### ISSUE THREAD

**Issue by mathieuhelie** [derhasi/composer-preserve-paths#7]
When attempting to preserve sites/default in Drupal, \Composer\Util\Filesystem->rename() does not actually rename the directory but passes control to ->copyThenRemove(), which then attempts to do what its name implies.

So if there are any protected files in the paths being preserved, PathPreserver->preserve() fails to complete and a RuntimeException is thrown that a file could not be deleted.

**Comment by derhasi** [comment]
@mathieuhelie, what system did this behaviour occur? Filesystem:rename() should use php's rename at first (see https://github.com/composer/composer/blob/master/src/Composer/Util/Filesystem.php#L273).
